id: P77C4D9A7
initial_creation_type: ocr
source_metadata:
  volumes:
    7ad244d1dcdc4033b46b208edb7f0311:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ལག་པའི་ཚད་ཀྱི་འགྲེལ་པ།
      total_pages: 1605
      volume_number: 57
